version: '3.8'
services:
  db:
    image: postgres:15-bullseye
    restart: unless-stopped
    env_file: .env
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD","pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:latest
    restart: no
    environment:
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      - FLYWAY_URL=jdbc:postgresql://db:${PGPORT}/${POSTGRES_DB}
      - FLYWAY_SCHEMAS=public
    command: -connectRetries=5 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      db:
        condition: service_healthy

  openfda-app:
    build: .
    container_name: openfda-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_PORT: ${OPENFDA_APP_PORT}
    ports:
      - "${OPENFDA_APP_PORT}:${OPENFDA_APP_PORT}"
    env_file: .env
